name: First Workflow

on:
#  push:
#     branches: 
#       - master
#  pull_request:
#     branches: 
#       - master

 workflow_dispatch:

jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
    
      - name: actions
        uses: actions/checkout@v3

      - name: Print
        run: echo "Hello World"

